[GERAL]

# Pasta onde estão os PDFs
PASTA_ENTRADA = C:\Users\Grupo DSC\Documents\Projetos\AutoRename\entrada

# Pasta onde ficará o log
PASTA_LOGS = logs

# Simular renomeação
DRY_RUN = False

DEBUG = False

[CONDOMINIOS]

PREFIXO_1 = COND.
PREFIXO_2 = RES.
PREFIXO_3 = CNJ.
PREFIXO_4 = ED.
PREFIXO_5 = CONDOMÍNIO
PREFIXO_6 = EDIFÍCIO
PREFIXO_7 = RESIDENCIAL
PREFIXO_8 = GPC
PREFIXO_9 = EDIFICIO
PREFIXO_10 = CONDOMINIO

[ALIAS_CONDOMINIOS]

ECOVILLA - CONDOMINIO VERDE = ECOVILLA
ADOLFO BLAESE-TORRE DONA CAMILA = DONA CAMILA
PORTÃO DE BRANDEMBURGO - BENDORF = BENDORF

[UNIDADES]

TIPO_1 = APARTAMENTO
TIPO_2 = CASA
TIPO_3 = SALA
TIPO_4 = BOX
TIPO_5 = GARAGEM

[BLOCOS]

TIPO_1 = BL
TIPO_2 = BLOCO
TIPO_3 = CS
TIPO_4 = TE

[FILTROS]

PALAVRAS_PARADA = RUA,AVENIDA,CEP,CNPJ,BANCO,PIX,AGÊNCIA,CONTA
