[GERAL]

# Pasta onde estão os PDFs
PASTA_ENTRADA =

# Pasta onde ficará o log
PASTA_LOGS = logs

# Simular renomeação
DRY_RUN = False

DEBUG = True

[CONDOMINIOS]

PREFIXO_1 = COND.
PREFIXO_2 = RES.
PREFIXO_3 = CNJ.
PREFIXO_4 = ED.
PREFIXO_5 = CONDOMÍNIO
PREFIXO_6 = EDIFÍCIO
PREFIXO_7 = RESIDENCIAL
PREFIXO_8 = GPC
PREFIXO_9 = EDIFICIO
PREFIXO_10 = CONDOMINIO

[ALIAS_CONDOMINIOS]

#COLOQUE ABAIXO O NOME QUE SAIU RENOMEADO ( = ) NOME QUE DEVERÁ SAIR

[UNIDADES]

TIPO_1 = APARTAMENTO
TIPO_2 = CASA
TIPO_3 = SALA
TIPO_4 = BOX
TIPO_5 = GARAGEM

[BLOCOS]

TIPO_1 = BL
TIPO_2 = BLOCO
TIPO_3 = CS
TIPO_4 = TE
TIPO_5 = SL
TIPO_6 = TORRE
TIPO_7 = T

[FILTROS]

PALAVRAS_PARADA = RUA,AVENIDA,CEP,CNPJ,BANCO,PIX,AGÊNCIA,CONTA

[DELIMITADORES_UNIDADE]

ITEM_1 = ID
ITEM_2 = CPF
ITEM_3 = CNPJ
ITEM_4 = CEP
ITEM_5 = RUA
ITEM_6 = AV
ITEM_7 = AVENIDA
ITEM_8 = Nº
ITEM_9 = NUMERO
ITEM_10 = BANCO
ITEM_11 = PIX
